spring.application.name=PawMarket

spring.datasource.url=jdbc:h2:mem:pawmarket
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
